version: "3"
# remember to use this compose file __ONLY__ for development/testing purposes

services:
    postgres:
        image: postgres:10.5-alpine
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "127.0.0.1:5432:5432"
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_PASSWORD=test
            - MYSQL_USER=test
            - MYSQL_DATABASE=test
        ports:
            - "127.0.0.1:3306:3306"
    redis:
        image: redis:4.0-alpine
        ports:
            - "127.0.0.1:6379:6379"